name: Conventional Commit Checker
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - dev

jobs:
  check_conventional_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name : Check PR Title
      run: |
          pr_title="${{ github.event.pull_request.title }}"
          
          # Conventional Commit regex pattern
          regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?: .+"
          
          if [[ ! $pr_title =~ $regex ]]; then
            echo "Error: PR title does not follow Conventional Commit format. Please ensure the title begins with one of the following types: feat, fix, docs, style, refactor, test, or chore."
            exit 1
          else
            echo "PR title is in Conventional Commit format."
          fi
